language: go

env:
  global:
    - CACHE_NAME=${TRAVIS_ARCH}
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org

os:
  - linux

go:
  - "1.15.1"

before_install:
  - mkdir -p ~/.config/namecheap/
  - touch ~/.config/namecheap/config.yml

cache:
  directories:
     - $HOME/gopath/pkg/mod
     - $HOME/.cache/go-build
